baseURL: "https://hellendev.com.br/"
languageCode: "en-us"
title: "Hellen Assis"
theme: "PaperMod"
params:
  socialIcons:
    - name: "LinkedIn"
      url: "https://linkedin.com/in/hellenassisdev/"
    - name: "GitHub"
      url: "https://github.com/hellenrga"

  homeInfoParams:
    Title: "Hi, I'm Hellen! ðŸ˜"
    content: >
      Welcome to my blog. Iâ€™m 19-year-old **Software Engineer** from **Brazil**.
      
      - Here, youâ€™ll find my thoughts on a variety of technical topics, including **Microsoft Azure, Kubernetes, Docker, Cloud-Native Technologies, DevOps, and Linux.**

menu:
  main:
    - identifier: About
      name: "About"
      url: /aboutme/
      weight: 10
    - identifier: "Index"
      name: "Index"
      url: /archives/
      weight: 30