baseURL: "https://hellendev.com.br/"
languageCode: "en-us"
title: "Hellen Assis"
theme: "PaperMod"
params:
  socialIcons:
    - name: "LinkedIn"
      url: "https://linkedin.com/in/hellenassisdev/"
    - name: "GitHub"
      url: "https://github.com/hellenrga"

  homeInfoParams:
    Title: "Welcome! ðŸ˜"
    content: >
      This is the website of **Hellen**, a **Software Engineer** from **Brazil**.
      
      - Here, youâ€™ll find my thoughts and learnings on a variety of technical topics, including **Microsoft Azure, Kubernetes, Docker, Cloud-Native Technologies, DevOps, and Linux.**

  # ShowShareButtons: true
  ShowReadingTime: true
  # ShowToc: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

menu:
  main:
    - identifier: About
      name: "About"
      url: /aboutme/
      weight: 10
    - identifier: "Index"
      name: "Index"
      url: /archives/
      weight: 30
    - identifier: "Tags"
      name: "Tags"
      url: /tags/
      weight: 30